#define PHANTOM_COROUTINES_COMPILER_CLANG_MSVC 1

#define PHANTOM_COROUTINES_MSVC_INSTRINSIC
#define PHANTOM_COROUTINES_MSVC_FORCEINLINE
#define PHANTOM_COROUTINES_MSVC_SUPPRESS_PACKING_ALIGNMENT_WARNING
#define PHANTOM_COROUTINES_MSVC_PUSH_DISABLE_WARNING(warnings)
#define PHANTOM_COROUTINES_MSVC_POP_WARNINGS()

// CLang captures the result of get_return_object using auto,
// which decays reference types. Therefore, get_return_object
// cannot return a reference type.
#define PHANTOM_COROUTINES_USE_REFERENCE_WRAPPER_RETURN_TYPE_FOR_GET_RETURN_OBJECT 1

#define PHANTOM_COROUTINES_LAMBDA_REFERENCE_IS_FIRST_ARGUMENT_OF_PROMISE_CONSTRUCTOR 0
#define PHANTOM_COROUTINES_FUTURE_DOESNT_ACCEPT_NOT_DEFAULT_CONSTRUCTIBLE 0
#define PHANTOM_COROUTINES_SYMMETRIC_TRANSFER_INCORRECTLY_LIFTED_TO_COROUTINE_FRAME 0
#define PHANTOM_COROUTINES_NO_REJECT_LAMBDA_WITH_INVALID_MEMBER 0

// CLang targetting Windows has a bug where exception data is not correctly when compiling with modules.
// https://github.com/llvm/llvm-project/issues/53486
#define PHANTOM_COROUTINES_INCORRECT_EXCEPTION_DATA_IN_MODULES 1
