#ifndef PHANTOM_COROUTINES_INCLUDE_CONFIG_GLOBALS_H
#define PHANTOM_COROUTINES_INCLUDE_CONFIG_GLOBALS_H

#ifndef PHANTOM_COROUTINES_COMPILING_MODULES
#include "config_macros.h"
#endif

static_assert(PHANTOM_COROUTINES_IS_CONFIGURED);
PHANTOM_COROUTINES_ASSERT_IS_MODULE;

namespace Phantom::Coroutines
{

PHANTOM_COROUTINES_MODULE_EXPORT
struct Config
{
    static constexpr bool Symmetric_Transfer_Incorrectly_Lifted_to_Coroutine_Frame
        = PHANTOM_COROUTINES_SYMMETRIC_TRANSFER_INCORRECTLY_LIFTED_TO_COROUTINE_FRAME;

    static constexpr bool No_Reject_Lambda_with_Invalid_Member
        = PHANTOM_COROUTINES_NO_REJECT_LAMBDA_WITH_INVALID_MEMBER;

    // PHANTOM_COROUTINES_LAMBDA_REFERENCE_IS_FIRST_ARGUMENT_OF_PROMISE_CONSTRUCTOR
    static constexpr bool Lambda_Reference_Is_First_Argument_Of_Promise_Constructor
        = PHANTOM_COROUTINES_LAMBDA_REFERENCE_IS_FIRST_ARGUMENT_OF_PROMISE_CONSTRUCTOR;
};

}

#endif // PHANTOM_COROUTINES_INCLUDE_CONFIG_GLOBALS_H
