#ifndef PHANTOM_COROUTINES_INCLUDE_CONFIG_MACROS_H
#define PHANTOM_COROUTINES_INCLUDE_CONFIG_MACROS_H

#if defined(_MSVC_LANG) && defined(__clang__)
// Using CLang in MSVC compatibility mode
#include "config_macros_clang_msvc.h"

#elif defined(_MSVC_LANG) && !defined(__clang__)
#include "config_macros_msvc.h"

#elif defined(__clang__) && !defined(_MSVC_LANG)
#include "config_macros_clang.h"

#else
#error "Unsupported compiler"
#endif

#if !NDEBUG
#ifndef PHANTOM_COROUTINES_THREAD_POOL_SCHEDULER_DETECT_ALL_THREADS_SLEEPING
#define PHANTOM_COROUTINES_THREAD_POOL_SCHEDULER_DETECT_ALL_THREADS_SLEEPING 1
#endif
#endif

#ifdef PHANTOM_COROUTINES_COMPILING_MODULES
#define PHANTOM_COROUTINES_MODULE_EXPORT export
#else
#define PHANTOM_COROUTINES_MODULE_EXPORT
#endif

#ifndef PHANTOM_COROUTINES_IS_COMPILED_MODULE
#define PHANTOM_COROUTINES_IS_COMPILED_MODULE 0
#endif

#ifndef PHANTOM_COROUTINES_ASSERT_IS_MODULE 
#if defined(PHANTOM_COROUTINES_TESTING_SINGLE_MODULE)
#define PHANTOM_COROUTINES_ASSERT_IS_MODULE static_assert(PHANTOM_COROUTINES_IS_COMPILED_MODULE)
#elif defined(PHANTOM_COROUTINES_TESTING_MODULES)
#define PHANTOM_COROUTINES_ASSERT_IS_MODULE static_assert(PHANTOM_COROUTINES_IS_COMPILED_MODULE)
#else
#define PHANTOM_COROUTINES_ASSERT_IS_MODULE static_assert(true)
#endif
#endif

#define PHANTOM_COROUTINES_IS_CONFIGURED 1

#endif // PHANTOM_COROUTINES_INCLUDE_CONFIG_MACROS_H
